# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - "internal/"
      - "*.go"
    carryforward: true

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "vendor/**"

